### ISSUE TITLE
Sprint 3 checklist

### ISSUE THREAD

**Issue by vaskes79** [vaskes79/middle.messenger.praktikum.yandex#81]
## router #78 

- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98
- [x] #99
 - [x] #100
 - [x] #101

## api #79 

Внедрите HTTP API чатов, авторизации и пользователей. [Описание API](https://ya-praktikum.tech/api/v2/swagger/#/) найдёте по ссылке. После регистрации пользователь должен попадать сразу на страницу чата. Также в уроках этого спринта описаны «ручки» и как делать к ним запросы. Нужно добавить:

- [x] #82
- [x] #83
- [x] #84
- [x] #85

## common tasks

- [x] #91
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90

## additional tasks

- [ ] Покройте тестами все утилиты из проекта;
- [ ] Реализуйте в проекте собственную сортировку, стек и очередь вместо использования стандартных sort, array.
- [ ] Настройте CSP (Content Security Policy) для статики в Express.
- [ ] Настройте защиту от всех уязвимостей по OWASP Top-10.
